server:
  port: 8084

spring:
  application:
    name: AUTH-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3307/bitlord_auth?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: bitlord123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics
  metrics:
    export:
      prometheus:
        enabled: true
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9412/api/v2/spans

app:
  jwt:
    # Please override this in production via environment variables
    secret: ${JWT_SECRET:4B697368616E5365637265744B6579466F724269746C6F726441707032303236}
    access-token-expiry: 900
    refresh-token-expiry: 604800

# docker exec -it <container_name> mysql -u root -p
#  docker exec -it bitlord-computer-parts-mysql-auth-1 mysql -u root -p